title: IndieHosters
email: info@indiehosters.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://indiehosters.net" # the base hostname & protocol for your site
twitter_username: indiehosters
github_username: indiehosters
facebook_username: indiehosters
googleplus_username: indiehosters

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

highlighter: true
collections:
  - carousel_items
  - products
